| ?column?                                                                                                                                                                                                                                                                                                                                                                                          |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| CREATE POLICY "Merchants can read their own transactions" ON "public"."transactions" AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1
   FROM stores
  WHERE ((stores.id = transactions.merchant_id) AND (stores.owner_id = auth.uid())))));                                                                                                                                          |
| CREATE POLICY "Customers can read their own transactions" ON "public"."transactions" AS PERMISSIVE FOR SELECT TO public USING ((customer_id = auth.uid()));                                                                                                                                                                                                                                       |
| CREATE POLICY "Les utilisateurs peuvent voir leurs propres favoris" ON "public"."saved_places" AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = user_id));                                                                                                                                                                                                                                 |
| CREATE POLICY "Les utilisateurs peuvent ajouter des favoris" ON "public"."saved_places" AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));                                                                                                                                                                                                                                   |
| CREATE POLICY "Les utilisateurs peuvent supprimer leurs favoris" ON "public"."saved_places" AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));                                                                                                                                                                                                                                    |
| CREATE POLICY "Admins can view all drivers" ON "public"."drivers" AS PERMISSIVE FOR SELECT TO public USING (((auth.jwt() ->> 'role'::text) = 'admin'::text));                                                                                                                                                                                                                                     |
| CREATE POLICY "Drivers can view their own data" ON "public"."drivers" AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = id));                                                                                                                                                                                                                                                               |
| CREATE POLICY "Admins can update drivers" ON "public"."drivers" AS PERMISSIVE FOR UPDATE TO public USING (((auth.jwt() ->> 'role'::text) = 'admin'::text));                                                                                                                                                                                                                                       |
| CREATE POLICY "Users can view their own friendships" ON "public"."friendships" AS PERMISSIVE FOR SELECT TO public USING (((auth.uid() = user_id) OR (auth.uid() = friend_id)));                                                                                                                                                                                                                   |
| CREATE POLICY "Users can send friendship requests" ON "public"."friendships" AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));                                                                                                                                                                                                                                              |
| CREATE POLICY "Users can update their own friendships" ON "public"."friendships" AS PERMISSIVE FOR UPDATE TO public USING (((auth.uid() = user_id) OR (auth.uid() = friend_id))) WITH CHECK (((auth.uid() = user_id) OR (auth.uid() = friend_id)));                                                                                                                                               |
| CREATE POLICY "Users can view their own messages" ON "public"."messages" AS PERMISSIVE FOR SELECT TO public USING (((auth.uid() = sender_id) OR (auth.uid() = receiver_id)));                                                                                                                                                                                                                     |
| CREATE POLICY "Users can send messages" ON "public"."messages" AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = sender_id));                                                                                                                                                                                                                                                          |
| CREATE POLICY "Users can upload chat attachments" ON "storage"."objects" AS PERMISSIVE FOR INSERT TO public WITH CHECK (((bucket_id = 'chat-attachments'::text) AND (auth.uid() IS NOT NULL) AND ((storage.foldername(name))[1] = (auth.uid())::text)));                                                                                                                                          |
| CREATE POLICY "Users can delete their own chat attachments" ON "storage"."objects" AS PERMISSIVE FOR DELETE TO public USING (((bucket_id = 'chat-attachments'::text) AND (auth.uid() IS NOT NULL) AND ((storage.foldername(name))[1] = (auth.uid())::text)));                                                                                                                                     |
| CREATE POLICY "Users can insert their own search history" ON "public"."user_search_history" AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));                                                                                                                                                                                                                        |
| CREATE POLICY "Allow authenticated uploads to reels" ON "storage"."objects" AS PERMISSIVE FOR INSERT TO public WITH CHECK (((bucket_id = 'reels'::text) AND (auth.role() = 'authenticated'::text)));                                                                                                                                                                                              |
| CREATE POLICY "Allow public view for reels" ON "storage"."objects" AS PERMISSIVE FOR SELECT TO public USING ((bucket_id = 'reels'::text));                                                                                                                                                                                                                                                        |
| CREATE POLICY "Anyone can view active reels" ON "public"."reels" AS PERMISSIVE FOR SELECT TO public USING ((status = 'active'::text));                                                                                                                                                                                                                                                            |
| CREATE POLICY "Store owners can insert their own reels" ON "public"."reels" AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() IN ( SELECT stores.owner_id
   FROM stores
  WHERE (stores.id = reels.store_id))));                                                                                                                                                                        |
| CREATE POLICY "Product images are publicly accessible" ON "storage"."objects" AS PERMISSIVE FOR SELECT TO public USING ((bucket_id = 'product-images'::text));                                                                                                                                                                                                                                    |
| CREATE POLICY "Store owners can upload product images" ON "storage"."objects" AS PERMISSIVE FOR INSERT TO public WITH CHECK (((bucket_id = 'product-images'::text) AND (auth.uid() IS NOT NULL) AND (((storage.foldername(name))[1])::bigint IN ( SELECT stores.id
   FROM stores
  WHERE (stores.owner_id = auth.uid())))));                                                                     |
| CREATE POLICY "Store owners can update product images" ON "storage"."objects" AS PERMISSIVE FOR UPDATE TO public USING (((bucket_id = 'product-images'::text) AND (((storage.foldername(name))[1])::bigint IN ( SELECT stores.id
   FROM stores
  WHERE (stores.owner_id = auth.uid())))));                                                                                                       |
| CREATE POLICY "Store owners can delete product images" ON "storage"."objects" AS PERMISSIVE FOR DELETE TO public USING (((bucket_id = 'product-images'::text) AND (((storage.foldername(name))[1])::bigint IN ( SELECT stores.id
   FROM stores
  WHERE (stores.owner_id = auth.uid())))));                                                                                                       |
| CREATE POLICY "Store images are publicly accessible" ON "storage"."objects" AS PERMISSIVE FOR SELECT TO public USING ((bucket_id = 'store-images'::text));                                                                                                                                                                                                                                        |
| CREATE POLICY "Store owners can upload store images" ON "storage"."objects" AS PERMISSIVE FOR INSERT TO public WITH CHECK (((bucket_id = 'store-images'::text) AND (auth.uid() IS NOT NULL) AND (((storage.foldername(name))[1])::bigint IN ( SELECT stores.id
   FROM stores
  WHERE (stores.owner_id = auth.uid())))));                                                                         |
| CREATE POLICY "Store owners can update store images" ON "storage"."objects" AS PERMISSIVE FOR UPDATE TO public USING (((bucket_id = 'store-images'::text) AND (((storage.foldername(name))[1])::bigint IN ( SELECT stores.id
   FROM stores
  WHERE (stores.owner_id = auth.uid())))));                                                                                                           |
| CREATE POLICY "Store owners can manage their own reels" ON "public"."reels" AS PERMISSIVE FOR ALL TO public USING ((auth.uid() IN ( SELECT stores.owner_id
   FROM stores
  WHERE (stores.id = reels.store_id))));                                                                                                                                                                                |
| CREATE POLICY "Store owners can delete store images" ON "storage"."objects" AS PERMISSIVE FOR DELETE TO public USING (((bucket_id = 'store-images'::text) AND (((storage.foldername(name))[1])::bigint IN ( SELECT stores.id
   FROM stores
  WHERE (stores.owner_id = auth.uid())))));                                                                                                           |
| CREATE POLICY "Store documents are private" ON "storage"."objects" AS PERMISSIVE FOR SELECT TO public USING (((bucket_id = 'store-documents'::text) AND ((((storage.foldername(name))[1])::bigint IN ( SELECT stores.id
   FROM stores
  WHERE (stores.owner_id = auth.uid()))) OR (EXISTS ( SELECT 1
   FROM users
  WHERE ((users.id = auth.uid()) AND (users.role = 'ADMIN'::user_role))))))); |
| CREATE POLICY "Store owners can upload documents" ON "storage"."objects" AS PERMISSIVE FOR INSERT TO public WITH CHECK (((bucket_id = 'store-documents'::text) AND (auth.uid() IS NOT NULL) AND (((storage.foldername(name))[1])::bigint IN ( SELECT stores.id
   FROM stores
  WHERE (stores.owner_id = auth.uid())))));                                                                         |
| CREATE POLICY "Store documents cannot be updated" ON "storage"."objects" AS PERMISSIVE FOR UPDATE TO public USING (false);                                                                                                                                                                                                                                                                        |
| CREATE POLICY "Only admins can delete store documents" ON "storage"."objects" AS PERMISSIVE FOR DELETE TO public USING (((bucket_id = 'store-documents'::text) AND (EXISTS ( SELECT 1
   FROM users
  WHERE ((users.id = auth.uid()) AND (users.role = 'ADMIN'::user_role))))));                                                                                                                  |
| CREATE POLICY "Review images are publicly accessible" ON "storage"."objects" AS PERMISSIVE FOR SELECT TO public USING ((bucket_id = 'review-images'::text));                                                                                                                                                                                                                                      |
| CREATE POLICY "Users can upload review images" ON "storage"."objects" AS PERMISSIVE FOR INSERT TO public WITH CHECK (((bucket_id = 'review-images'::text) AND (auth.uid() IS NOT NULL)));                                                                                                                                                                                                         |
| CREATE POLICY "Review images cannot be updated" ON "storage"."objects" AS PERMISSIVE FOR UPDATE TO public USING (false);                                                                                                                                                                                                                                                                          |
| CREATE POLICY "subscriptions_delete" ON "public"."subscriptions" AS PERMISSIVE FOR DELETE TO public USING (is_admin());                                                                                                                                                                                                                                                                           |
| CREATE POLICY "Authors can delete review images" ON "storage"."objects" AS PERMISSIVE FOR DELETE TO public USING (((bucket_id = 'review-images'::text) AND (((auth.uid())::text = (storage.foldername(name))[1]) OR (EXISTS ( SELECT 1
   FROM users
  WHERE ((users.id = auth.uid()) AND (users.role = 'ADMIN'::user_role)))))));                                                                |
| CREATE POLICY "Avatars are publicly accessible" ON "storage"."objects" AS PERMISSIVE FOR SELECT TO public USING ((bucket_id = 'avatars'::text));                                                                                                                                                                                                                                                  |
| CREATE POLICY "Users can upload their own avatar" ON "storage"."objects" AS PERMISSIVE FOR INSERT TO public WITH CHECK (((bucket_id = 'avatars'::text) AND (auth.uid() IS NOT NULL) AND ((auth.uid())::text = (storage.foldername(name))[1])));                                                                                                                                                   |
| CREATE POLICY "Users can update their own avatar" ON "storage"."objects" AS PERMISSIVE FOR UPDATE TO public USING (((bucket_id = 'avatars'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])));                                                                                                                                                                                     |
| CREATE POLICY "Users can delete their own avatar" ON "storage"."objects" AS PERMISSIVE FOR DELETE TO public USING (((bucket_id = 'avatars'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])));                                                                                                                                                                                     |
| CREATE POLICY "Public Access to Reels" ON "storage"."objects" AS PERMISSIVE FOR SELECT TO public USING ((bucket_id = 'reels'::text));                                                                                                                                                                                                                                                             |
| CREATE POLICY "Store owners can upload reels" ON "storage"."objects" AS PERMISSIVE FOR INSERT TO public WITH CHECK (((bucket_id = 'reels'::text) AND (auth.uid() IS NOT NULL)));                                                                                                                                                                                                                  |
| CREATE POLICY "Business owner can create their store" ON "public"."stores" AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((owner_id = auth.uid()));                                                                                                                                                                                                                                        |
| CREATE POLICY "Allow public read access" ON "public"."business_directory_tunisia" AS PERMISSIVE FOR SELECT TO public USING (true);                                                                                                                                                                                                                                                                |
| CREATE POLICY "Utilisateurs peuvent insérer leurs propres interactions" ON "public"."user_interactions" AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));                                                                                                                                                                                                                   |
| CREATE POLICY "Utilisateurs peuvent supprimer leurs propres interactions" ON "public"."user_interactions" AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));                                                                                                                                                                                                                      |
| CREATE POLICY "Tout le monde peut voir les interactions" ON "public"."user_interactions" AS PERMISSIVE FOR SELECT TO public USING (true);                                                                                                                                                                                                                                                         |
| CREATE POLICY "Utilisateurs authentifiés peuvent commenter" ON "public"."reel_comments" AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));                                                                                                                                                                                                                                   |
| CREATE POLICY "stories_bucket_public_read" ON "storage"."objects" AS PERMISSIVE FOR SELECT TO public USING ((bucket_id = 'stories'::text));                                                                                                                                                                                                                                                       |
| CREATE POLICY "stories_bucket_authenticated_insert" ON "storage"."objects" AS PERMISSIVE FOR INSERT TO public WITH CHECK (((bucket_id = 'stories'::text) AND (auth.role() = 'authenticated'::text)));                                                                                                                                                                                             |
| CREATE POLICY "stories_bucket_owner_delete" ON "storage"."objects" AS PERMISSIVE FOR DELETE TO public USING (((bucket_id = 'stories'::text) AND (owner = auth.uid())));                                                                                                                                                                                                                           |
| CREATE POLICY "Utilisateurs peuvent supprimer leurs propres commentaires" ON "public"."reel_comments" AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));                                                                                                                                                                                                                          |
| CREATE POLICY "Tout le monde peut voir les commentaires" ON "public"."reel_comments" AS PERMISSIVE FOR SELECT TO public USING (true);                                                                                                                                                                                                                                                             |
| CREATE POLICY "Tout le monde peut voir les stats" ON "public"."reel_stats" AS PERMISSIVE FOR SELECT TO public USING (true);                                                                                                                                                                                                                                                                       |
| CREATE POLICY "Le système peut mettre à jour les stats" ON "public"."reel_stats" AS PERMISSIVE FOR UPDATE TO public USING (true);                                                                                                                                                                                                                                                                 |
| CREATE POLICY "promotions_owner_all" ON "public"."promotions" AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1
   FROM stores
  WHERE ((stores.id = promotions.store_id) AND (stores.owner_id = auth.uid())))));                                                                                                                                                                         |
| CREATE POLICY "Owners can manage items for their promotions" ON "public"."promotion_items" AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1
   FROM (promotions p
     JOIN stores s ON ((p.store_id = s.id)))
  WHERE ((p.id = promotion_items.promotion_id) AND (s.owner_id = auth.uid())))));                                                                                         |
| CREATE POLICY "Public can read promotion items" ON "public"."promotion_items" AS PERMISSIVE FOR SELECT TO public USING (true);                                                                                                                                                                                                                                                                    |
| CREATE POLICY "Store owners can manage their tickets" ON "public"."support_tickets" AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1
   FROM stores
  WHERE ((stores.id = support_tickets.store_id) AND (stores.owner_id = auth.uid())))));                                                                                                                                              |
| CREATE POLICY "Customers can view their own tickets" ON "public"."support_tickets" AS PERMISSIVE FOR SELECT TO public USING ((customer_id = auth.uid()));                                                                                                                                                                                                                                         |
| CREATE POLICY "Users can view messages for tickets they have access to" ON "public"."support_messages" AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1
   FROM support_tickets
  WHERE (support_tickets.id = support_messages.ticket_id))));                                                                                                                                         |
| CREATE POLICY "Users can send messages for tickets they have access to" ON "public"."support_messages" AS PERMISSIVE FOR INSERT TO public WITH CHECK ((EXISTS ( SELECT 1
   FROM support_tickets
  WHERE (support_tickets.id = support_messages.ticket_id))));                                                                                                                                    |
| CREATE POLICY "Users can read own profile" ON "public"."profiles" AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = id));                                                                                                                                                                                                                                                                   |
| CREATE POLICY "Users can update own profile (except role)" ON "public"."profiles" AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = id)) WITH CHECK (((auth.uid() = id) AND (role = ( SELECT profiles_1.role
   FROM profiles profiles_1
  WHERE (profiles_1.id = auth.uid())))));                                                                                                          |
| CREATE POLICY "Allow public read service_directory" ON "public"."service_directory" AS PERMISSIVE FOR SELECT TO anon, authenticated USING (true);                                                                                                                                                                                                                                                 |
| CREATE POLICY "Users can update messages they are part of" ON "public"."messages" AS PERMISSIVE FOR UPDATE TO public USING (((auth.uid() = sender_id) OR (auth.uid() = receiver_id))) WITH CHECK (((auth.uid() = sender_id) OR (auth.uid() = receiver_id)));                                                                                                                                      |
| CREATE POLICY "Users can delete their own sent messages" ON "public"."messages" AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = sender_id));                                                                                                                                                                                                                                              |
| CREATE POLICY "users_select" ON "public"."users" AS PERMISSIVE FOR SELECT TO public USING (true);                                                                                                                                                                                                                                                                                                 |
| CREATE POLICY "users_insert" ON "public"."users" AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = id));                                                                                                                                                                                                                                                                               |
| CREATE POLICY "users_update" ON "public"."users" AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = id)) WITH CHECK ((auth.uid() = id));                                                                                                                                                                                                                                                     |
| CREATE POLICY "users_delete" ON "public"."users" AS PERMISSIVE FOR DELETE TO public USING (false);                                                                                                                                                                                                                                                                                                |
| CREATE POLICY "stores_select" ON "public"."stores" AS PERMISSIVE FOR SELECT TO public USING (((status = 'PUBLISHED'::store_status) OR (owner_id = auth.uid()) OR is_admin()));                                                                                                                                                                                                                    |
| CREATE POLICY "stores_insert" ON "public"."stores" AS PERMISSIVE FOR INSERT TO public WITH CHECK (((owner_id = auth.uid()) AND (auth.uid() IS NOT NULL)));                                                                                                                                                                                                                                        |
| CREATE POLICY "stores_update" ON "public"."stores" AS PERMISSIVE FOR UPDATE TO public USING (((owner_id = auth.uid()) OR is_admin())) WITH CHECK (((owner_id = auth.uid()) OR is_admin()));                                                                                                                                                                                                       |
| CREATE POLICY "stores_delete" ON "public"."stores" AS PERMISSIVE FOR DELETE TO public USING (is_admin());                                                                                                                                                                                                                                                                                         |
| CREATE POLICY "items_select" ON "public"."items" AS PERMISSIVE FOR SELECT TO public USING (((status = 'AVAILABLE'::item_status) OR (EXISTS ( SELECT 1
   FROM stores
  WHERE ((stores.id = items.store_id) AND (stores.owner_id = auth.uid())))) OR is_admin()));                                                                                                                                 |
| CREATE POLICY "items_insert" ON "public"."items" AS PERMISSIVE FOR INSERT TO public WITH CHECK ((EXISTS ( SELECT 1
   FROM stores
  WHERE ((stores.id = items.store_id) AND (stores.owner_id = auth.uid())))));                                                                                                                                                                                   |
| CREATE POLICY "items_update" ON "public"."items" AS PERMISSIVE FOR UPDATE TO public USING ((EXISTS ( SELECT 1
   FROM stores
  WHERE ((stores.id = items.store_id) AND (stores.owner_id = auth.uid()))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM stores
  WHERE ((stores.id = items.store_id) AND (stores.owner_id = auth.uid())))));                                                             |
| CREATE POLICY "items_delete" ON "public"."items" AS PERMISSIVE FOR DELETE TO public USING (((EXISTS ( SELECT 1
   FROM stores
  WHERE ((stores.id = items.store_id) AND (stores.owner_id = auth.uid())))) OR is_admin()));                                                                                                                                                                        |
| CREATE POLICY "schedules_select" ON "public"."service_schedules" AS PERMISSIVE FOR SELECT TO public USING (true);                                                                                                                                                                                                                                                                                 |
| CREATE POLICY "schedules_insert" ON "public"."service_schedules" AS PERMISSIVE FOR INSERT TO public WITH CHECK ((EXISTS ( SELECT 1
   FROM (items
     JOIN stores ON ((items.store_id = stores.id)))
  WHERE ((items.id = service_schedules.item_id) AND (stores.owner_id = auth.uid())))));                                                                                                     |
| CREATE POLICY "schedules_update" ON "public"."service_schedules" AS PERMISSIVE FOR UPDATE TO public USING ((EXISTS ( SELECT 1
   FROM (items
     JOIN stores ON ((items.store_id = stores.id)))
  WHERE ((items.id = service_schedules.item_id) AND (stores.owner_id = auth.uid())))));                                                                                                          |
| CREATE POLICY "schedules_delete" ON "public"."service_schedules" AS PERMISSIVE FOR DELETE TO public USING ((EXISTS ( SELECT 1
   FROM (items
     JOIN stores ON ((items.store_id = stores.id)))
  WHERE ((items.id = service_schedules.item_id) AND (stores.owner_id = auth.uid())))));                                                                                                          |
| CREATE POLICY "orders_select" ON "public"."orders" AS PERMISSIVE FOR SELECT TO public USING (((customer_id = auth.uid()) OR (EXISTS ( SELECT 1
   FROM stores
  WHERE ((stores.id = orders.store_id) AND (stores.owner_id = auth.uid())))) OR is_admin()));                                                                                                                                       |
| CREATE POLICY "orders_insert" ON "public"."orders" AS PERMISSIVE FOR INSERT TO public WITH CHECK (((auth.uid() IS NOT NULL) AND (customer_id = auth.uid())));                                                                                                                                                                                                                                     |
| CREATE POLICY "orders_update" ON "public"."orders" AS PERMISSIVE FOR UPDATE TO public USING (((EXISTS ( SELECT 1
   FROM stores
  WHERE ((stores.id = orders.store_id) AND (stores.owner_id = auth.uid())))) OR is_admin()));                                                                                                                                                                     |
| CREATE POLICY "orders_delete" ON "public"."orders" AS PERMISSIVE FOR DELETE TO public USING (false);                                                                                                                                                                                                                                                                                              |
| CREATE POLICY "bookings_select" ON "public"."bookings" AS PERMISSIVE FOR SELECT TO public USING (((customer_id = auth.uid()) OR (EXISTS ( SELECT 1
   FROM stores
  WHERE ((stores.id = bookings.store_id) AND (stores.owner_id = auth.uid())))) OR is_admin()));                                                                                                                                 |
| CREATE POLICY "bookings_insert" ON "public"."bookings" AS PERMISSIVE FOR INSERT TO public WITH CHECK (((auth.uid() IS NOT NULL) AND (customer_id = auth.uid())));                                                                                                                                                                                                                                 |
| CREATE POLICY "bookings_update" ON "public"."bookings" AS PERMISSIVE FOR UPDATE TO public USING (((EXISTS ( SELECT 1
   FROM stores
  WHERE ((stores.id = bookings.store_id) AND (stores.owner_id = auth.uid())))) OR is_admin()));                                                                                                                                                               |
| CREATE POLICY "bookings_delete" ON "public"."bookings" AS PERMISSIVE FOR DELETE TO public USING (false);                                                                                                                                                                                                                                                                                          |
| CREATE POLICY "reviews_select" ON "public"."reviews" AS PERMISSIVE FOR SELECT TO public USING ((((is_approved = true) AND (is_spam = false)) OR (author_id = auth.uid()) OR (EXISTS ( SELECT 1
   FROM stores
  WHERE ((stores.id = reviews.store_id) AND (stores.owner_id = auth.uid())))) OR is_admin()));                                                                                      |
| CREATE POLICY "reviews_insert" ON "public"."reviews" AS PERMISSIVE FOR INSERT TO public WITH CHECK (((auth.uid() IS NOT NULL) AND (author_id = auth.uid())));                                                                                                                                                                                                                                     |
| CREATE POLICY "reviews_update" ON "public"."reviews" AS PERMISSIVE FOR UPDATE TO public USING ((((author_id = auth.uid()) AND (created_at > (now() - '48:00:00'::interval))) OR (EXISTS ( SELECT 1
   FROM stores
  WHERE ((stores.id = reviews.store_id) AND (stores.owner_id = auth.uid())))) OR is_admin()));                                                                                  |
| CREATE POLICY "reviews_delete" ON "public"."reviews" AS PERMISSIVE FOR DELETE TO public USING (is_admin());                                                                                                                                                                                                                                                                                       |
| CREATE POLICY "subscriptions_select" ON "public"."subscriptions" AS PERMISSIVE FOR SELECT TO public USING (((user_id = auth.uid()) OR is_admin()));                                                                                                                                                                                                                                               |
| CREATE POLICY "subscriptions_insert" ON "public"."subscriptions" AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_admin());                                                                                                                                                                                                                                                                      |
| CREATE POLICY "subscriptions_update" ON "public"."subscriptions" AS PERMISSIVE FOR UPDATE TO public USING (is_admin());                                                                                                                                                                                                                                                                           |